Document: libpantheon
Title: Debian libpantheon Manual
Author: <insert document author here>
Abstract: This manual describes what libpantheon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpantheon/libpantheon.sgml.gz

Format: postscript
Files: /usr/share/doc/libpantheon/libpantheon.ps.gz

Format: text
Files: /usr/share/doc/libpantheon/libpantheon.text.gz

Format: HTML
Index: /usr/share/doc/libpantheon/html/index.html
Files: /usr/share/doc/libpantheon/html/*.html
